# Student's Biodata
name= input("Enter your name: ")
matric_no =input("Enter your matric no: ")
Date_of_Birth =input("Enter your Date of Birth: ")
Sex= input("Enter your sex: ")
Dept= input("Enter your dept: ")
Level= input("Enter your Level: ")
Year= input("Enter your Year: ")
Age=input("Enter your Age: ")
G_P=input("Enter your G_P: ")
Weight=input("Enter your weight: ")
isMuslim = input("are you a muslim: ")

print("Your name is: ", name)
print("Your matric no is: ", matric_no)
print("Your Date of birth is: ", Date_of_Birth)
print("Your sex is: ", Sex)
print("Your dept is: ", Dept)
print("Your level is: ", Level)
print("Your year is: ", Year)
print("Your age is: ", Age)
print("Your Grade Point is: ", G_P)
print("Your weight is: ", Weight)
print("are u a muslim: ", isMuslim)
